name: hexlet/code
on: push
jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHP Composer
        uses: baschny/php-composer-action@v1
      - run: make lint
      - run: make test